# data_utils
data_path: ../data/reviews_Video_Games_5.json.gz
min_user_interactions: 5
min_item_interactions: 5
required_columns:
  - reviewerID
  - asin
  - unixReviewTime

# model
batch_size: 32
lr: 0.001
max_len: 50
hidden_units: 128
num_blocks: 3
num_epochs: 2
num_heads: 1
dropout_rate: 0.5
n_workers: 3
l2_emb: 0.0